<!DOCTYPE html>
<!--	Author: 	Jeremiah Roland
		Date:		September 26, 2017
		File:		misspelledWords.php
		Purpose: 	Assignment 4
-->
<html>
<head>
	<title>Misspelled Words</title>
	<link rel ="stylesheet" type="text/css" href="HW4_CSS.css"> 
</head>
<body>
	<h1>Misspelled Words</h1> 
	<?php
		$randomWords = array(); 
		$characters = "abcdefghijklmnopqrstuvwxyz"; 
		$charLength = strlen($characters); 
		//outer loop to generate a random assortment of letter 1000 times 
		for($i = 0; $i < 1000; $i++)
		{
			//length generates a random letter between 3 and 7 inclusive 
			//random is the random string generated by the inner loop 
			$length = rand(3, 7); 
			$random = "";
			//inner loop generates a random string of a random length (between 3 and 7) 
			for($j = 0; $j < $length; $j++)
			{
				$random .= $characters[rand(0, $charLength -1)];
			}
			//add the random word to the randomWord array 
			$randomWords[] = $random; 
		}
		//print("<pre>");
		//print_r($randomWords);
		//print("</pre>");
		
		//read in the words from the dictionary file and save them to an array 
		$lines = file("engmix.txt", FILE_IGNORE_NEW_LINES); 
		$realWords = array(); 
		$fakeWords = array(); 
		//finds the string values in randomWords that are in the lines array 
		for ($o = 0; $o < count($randomWords); $o++) 
		{
			if (in_array($randomWords[$o], $lines)) 
			{
				$realWords[] = $randomWords[$o]; 
			}
			else
			{
				$fakeWords[] = $randomWords[$o]; 
			}
		}
		//print("<p>Here are the real words</p>"); 
		//print("<pre>");
		//print_r($realWords);
		//print("</pre>");
		
		//print("<p>Here are the fake words</p>"); 
		//print("<pre>");
		//print_r($fakeWords);
		//print("</pre>");
	?> 		
		<table> 
			<table border = "2">
			<tr> <th>Real Words</th> </tr>
	<?php
		//print the frequencies and percentages to the screen and write them to a file 
		//format: letter: freq. : %
		for($p = 0; $p < count($realWords); $p++)
		{
			 $thisWord = $realWords[$p]; 
		
			
	?> 
				<tr> 
					<th><?php echo $thisWord ?></th>
				</tr>
	<?php
		}
		
	?>
		</table> 
		//use a blank line to make it look a little nicer 
		<p></p>
			<table> 
			<table border = "2">
			<tr> <th>Fake Words</th> </tr>
	<?php
		//print the frequencies and percentages to the screen and write them to a file 
		//format: letter: freq. : %
		for($p = 0; $p < count($fakeWords); $p++)
		{
			 $thisWord = $fakeWords[$p]; 
		
			
	?> 
				<tr> 
					<th><?php echo $thisWord ?></th>
				</tr>
	<?php
		}
	?>
		</table> 
	
</body>
</html> 
